name: Build and Push Multi-Arch Docker Images

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'PROJECT'
      - 'README.md'
      - 'SECURITY.md'
      - 'images/worker/gpubench/**'
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  pre-build:
    runs-on: ubuntu-latest

    outputs:
      UNSTABLE: ${{ steps.set-env.outputs.unstable }}

    steps:
      - name: Set environment to global output variables based on branch
        id: set-env
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "unstable=false" >> $GITHUB_OUTPUT
          else
            echo "unstable=true" >> $GITHUB_OUTPUT
          fi

      - name: Print UNSTABLE from output
        run: |
          echo "Branch is - ${{ github.ref }}"
          echo "UNSTABLE - ${{ steps.set-env.outputs.unstable }}"

  build-and-push:
    runs-on: ubuntu-latest
    needs: pre-build

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU for Multi-Arch
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug vars
        run: |
          echo "UNSTABLE - is ${{ needs.pre-build.outputs.unstable }}"
          make get-version UNSTABLE=${{ needs.pre-build.outputs.unstable }}

      - name: Check if version synced
        run: make test-version-sync

      - name: Update CRDs and Run Tests
        run: |
          echo "Updating CRDs & auto-generated code (included in test step) & run tests"
          make test UNSTABLE=${{ needs.pre-build.outputs.unstable }}

      - name: Build and Push worker_slurmd Image
        run: |
          make docker-build UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=worker_slurmd DOCKERFILE=worker/slurmd.dockerfile
          make docker-push UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=worker_slurmd

      - name: Build and Push controller_slurmctld Image
        run: |
          make docker-build UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=controller_slurmctld DOCKERFILE=controller/slurmctld.dockerfile
          make docker-push UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=controller_slurmctld

      - name: Build and Push controller_slurmdbd Image
        run: |
          make docker-build UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=controller_slurmdbd DOCKERFILE=accounting/slurmdbd.dockerfile
          make docker-push UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=controller_slurmdbd

      - name: Build and Push login_sshd Image
        run: |
          make docker-build UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=login_sshd DOCKERFILE=login/sshd.dockerfile
          make docker-push UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=login_sshd

      - name: Build and Push munge Image
        run: |
          make docker-build UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=munge DOCKERFILE=munge/munge.dockerfile
          make docker-push UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=munge

      - name: Build and Push nccl_benchmark Image
        run: |
          make docker-build UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=nccl_benchmark DOCKERFILE=nccl_benchmark/nccl_benchmark.dockerfile
          make docker-push UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=nccl_benchmark

      - name: Build and Push exporter Image
        run: |
          make docker-build UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=exporter DOCKERFILE=exporter/exporter.dockerfile
          make docker-push UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=exporter

      - name: Build and Push slurmrestd Image
        run: |
          make docker-build UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=slurmrestd DOCKERFILE=restd/slurmrestd.dockerfile
          make docker-push UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=slurmrestd

      - name: Build tarball for jail
        run: |
          echo "Removing previous jail rootfs tar archive"
          rm -rf images/jail_rootfs.tar

          echo "Building tarball for jail"
          make docker-build UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=jail DOCKERFILE=jail/jail.dockerfile DOCKER_OUTPUT="--output type=tar,dest=jail_rootfs.tar"
          echo "Built tarball jail_rootfs.tar"

      - name: Build and Push Populate Jail Image
        run: |
          make docker-build UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=populate_jail DOCKERFILE=populate_jail/populate_jail.dockerfile
          make docker-push UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=populate_jail

      - name: Build and Push Operator Image
        run: |
          UNSTABLE=${{ needs.pre-build.outputs.unstable }}
          OPERATOR_IMAGE_TAG=$(make get-operator-tag-version UNSTABLE=${UNSTABLE})

          make docker-build UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=slurm-operator DOCKERFILE=Dockerfile IMAGE_VERSION=${OPERATOR_IMAGE_TAG}
          make docker-push UNSTABLE=${{ needs.pre-build.outputs.unstable }} IMAGE_NAME=slurm-operator IMAGE_VERSION=${OPERATOR_IMAGE_TAG}

      - name: Release Helm Charts
        run: |
          UNSTABLE=${{ needs.pre-build.outputs.unstable }}
          OPERATOR_IMAGE_TAG=$(make get-operator-tag-version UNSTABLE=${UNSTABLE})
          echo "Pushing Helm charts"
          make release-helm UNSTABLE=${UNSTABLE} OPERATOR_IMAGE_TAG=${OPERATOR_IMAGE_TAG}
