name: Build Multi-Arch Images

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'PROJECT'
      - 'README.md'
      - 'SECURITY.md'
      - 'images/worker/gpubench/**'
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build-and-push:
    runs-on: self-hosted

    strategy:
      matrix:
        platform: [linux/arm64]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.10.4
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install GO
        uses: actions/setup-go@v5.3.0
        with:
          go-version-file: 'go.mod'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        run: |
          IMAGES=(worker_slurmd controller_slurmctld controller_slurmdbd login_sshd munge nccl_benchmark exporter slurmrestd)
          for IMAGE_NAME in "${IMAGES[@]}"; do
            echo "Building image $IMAGE_NAME for platform ${{ matrix.platform }}"
            docker buildx build \
              --platform ${{ matrix.platform }} \
              --file images/$IMAGE_NAME/${IMAGE_NAME//_/.}.dockerfile \
              --tag ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest \
              --tag ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:${{ github.sha }} \
              --push images/$IMAGE_NAME
          done

      - name: Build Operator Image
        run: |
          docker buildx build \
            --platform ${{ matrix.platform }} \
            --file Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/slurm-operator:latest \
            --tag ghcr.io/${{ github.repository_owner }}/slurm-operator:${{ github.sha }} \
            --push .
